version: 1
name: convex
subProject: convex-core
source:
  extensionClass: edu.uic.bitslab.propcov.extensions.source.Git
  properties:
    checkoutID: e6db05a611cd4a1fb51f959e20d246637bb7744a
    URL: https://github.com/Convex-Dev/convex.git
patchName: artifacts/configs/convex/convex.patch
mainJar: convex-core-0.7.1.jar
mainJarWithDependencies: convex-core-0.7.1-jar-with-dependencies.jar
testJar: convex-core-0.7.1-tests.jar
buildSystem:
  extensionClass: edu.uic.bitslab.propcov.extensions.buildsystem.Maven
  properties:
    mvnOptions: -DfailIfNoTests=false
testFramework:
  extensionClass: edu.uic.bitslab.propcov.extensions.testframework.JunitQuickCheck
analysisFramework:
  extensionClass: edu.uic.bitslab.propcov.extensions.analysisframework.Opal
  properties:
    AnalysisType: CFA0
timeouts:
  dotGeneration: 0
coverage:
  extensionClass: edu.uic.bitslab.propcov.extensions.coverage.JaCoCo
properties:
- name: GenTestFormat#messageRoundTrip
  entryPoint: convex.comms.GenTestFormat.messageRoundTrip(Ljava/lang/String;)V
- name: GenTestFormat#primitiveRoundTrip
  entryPoint: convex.comms.GenTestFormat.primitiveRoundTrip(Lconvex/core/data/ACell;)V
- name: GenTestFormat#dataRoundTrip
  entryPoint: convex.comms.GenTestFormat.dataRoundTrip(Lconvex/core/data/ACell;)V
