version: 1
name: jlens
source:
  extensionClass: edu.uic.bitslab.propcov.extensions.source.Git
  properties:
    checkoutID: 8cc5cd9c0feca7ed6ba85e0da6d90c9cc3173e96
    URL: https://github.com/dannicolici/jLens.git
patchName: artifacts/configs/jlens/jlens.patch
mainJar: jlens-1.1.0.jar
mainJarWithDependencies: jlens-1.1.0-jar-with-dependencies.jar
testJar: jlens-1.1.0-tests.jar
buildSystem:
  extensionClass: edu.uic.bitslab.propcov.extensions.buildsystem.Maven
testFramework:
  extensionClass: edu.uic.bitslab.propcov.extensions.testframework.JunitQuickCheck
analysisFramework:
  extensionClass: edu.uic.bitslab.propcov.extensions.analysisframework.Opal
coverage:
  extensionClass: edu.uic.bitslab.propcov.extensions.coverage.JaCoCo
properties:
- name: PropertyOperationsQuickCheckTest#bulkTransformOperationsAreAppliedInOrder
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.bulkTransformOperationsAreAppliedInOrder(I)V
- name: PropertyOperationsQuickCheckTest#commutativeConcurrentTransformationsAreSafeForDifferentProperties
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.commutativeConcurrentTransformationsAreSafeForDifferentProperties(ILjava/lang/String;)V
- name: PropertyOperationsQuickCheckTest#commutativeConcurrentTransformationsAreSafeForDifferentPropertiesUsingCustomExecutor
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.commutativeConcurrentTransformationsAreSafeForDifferentPropertiesUsingCustomExecutor(ILjava/lang/String;)V
- name: PropertyOperationsQuickCheckTest#hookRunsForAllValuesAndOncePerBulkTransformation
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.hookRunsForAllValuesAndOncePerBulkTransformation(I)V
- name: PropertyOperationsQuickCheckTest#hookRunsForAllValuesAndSingleTransformations
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.hookRunsForAllValuesAndSingleTransformations(I)V
- name: PropertyOperationsQuickCheckTest#transformOperationsAreAppliedInOrder
  entryPoint: ro.bitgloss.PropertyOperationsQuickCheckTest.transformOperationsAreAppliedInOrder(I)V
- name: PropertyQuickCheckTest#getBackWhatYouPutIn
  entryPoint: ro.bitgloss.PropertyQuickCheckTest.getBackWhatYouPutIn(Ljava/lang/Integer;)V
- name: PropertyQuickCheckTest#puttingBackWhatYouGotDoesNotChangeTheProperty
  entryPoint: ro.bitgloss.PropertyQuickCheckTest.puttingBackWhatYouGotDoesNotChangeTheProperty(Ljava/lang/Integer;)V
- name: PropertyQuickCheckTest#settingTwiceIsTheSameAsSettingOnce
  entryPoint: ro.bitgloss.PropertyQuickCheckTest.settingTwiceIsTheSameAsSettingOnce(Ljava/lang/Integer;)V
